services:
- docker:dind

stages:
- build
- test

variables:
  TEST_IMAGE: registry.gitlab.com/$CI_PROJECT_NAMESPACE/gitlab-development-kit:$CI_BUILD_REF_NAME

build:image:
  image: docker:git
  stage: build
  script:
    #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    #- docker pull $TEST_IMAGE
    #- docker build -t $TEST_IMAGE .
    #- docker push $TEST_IMAGE
    # taken from https://gitlab.com/gitlab-org/gitlab-qa/blob/master/.gitlab-ci.yml
    - ./bin/docker load
    - ./bin/docker build
    - ./bin/docker store
    - test -n "$CI_BUILD_TOKEN" || exit 0
    - ./bin/docker publish
  # when: manual
  cache:
      key: "docker-build-cache"
      paths:
        - ./latest_image.tar
test:install:
  image: $TEST_IMAGE
  stage: test
  script:
    - cd gem
    - bash -l -c "gem build gitlab-development-kit.gemspec"
    - bash -l -c "gem install gitlab-development-kit-*.gem"
    - cd /home/gdk
    - bash -l -c "gdk init"
    - cd gitlab-development-kit
    - bash -l -c "gdk install"
    - support/set-gitlab-upstream
    - bash -l -c "gdk run" &
    - sleep 10
    - curl -f http://127.0.0.1:3000/

