services:
- docker:dind

stages:
- build
- test

variables:
  TEST_IMAGE: registry.gitlab.com/rubycut/gitlab-development-kit:$CI_BUILD_REF_NAME

build:image:
  image: docker:git
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
  when: manual

test:install:
  image: $TEST_IMAGE
  stage: test
  script:
    #- bash test_ubuntu.sh
    - cd gem && gem build gitlab-development-kit.gemspec && gem install gitlab-development-kit-*.gem
    - cd /home/gdk && sudo -H -u gdk bash -l gdk init
    - cd gitlab-development-kit
    - sudo -H -u gdk bash -l gdk install
    - sudo -H -u gdk bash -l support/set-gitlab-upstream
    - sudo -H -u gdk bash -l gdk run &
    - sleep 10
    - curl http://127.0.0.1:3000/

