services:
- docker:dind

stages:
- build
- test

variables:
  CONTAINER_TEST_IMAGE: gitlab-gtk:$CI_BUILD_REF_NAME

build_prerequisites:
  image: docker:git
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .

build_env:
  image: $CONTAINER_TEST_IMAGE
  stage: build
  script:
    - bash test_ubuntu.sh