services:
- docker:dind

stages:
- build
- test

variables:
  TEST_IMAGE: registry.gitlab.com/rubycut/gitlab-development-kit:$CI_BUILD_REF_NAME

build:image:
  image: docker:git
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
  when: manual

test:install:
  image: $TEST_IMAGE
  stage: test
  script:
    - bash test_ubuntu.sh