pages:
  stage: deploy
  needs:
    - job: yard
      artifacts: true
  script:
    - cp -r yard public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

deploy-gitpod-workspace-image:
  stage: deploy
  extends:
    - .docker:use-docker-in-docker
  image: docker:git
  before_script:
    - apk add --no-cache jq curl
  script:
    - ./support/docker ci-login
    - ./support/gitpod/docker-tag-image-as-stable
  after_script:
    - ./support/docker ci-logout
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: manual
