pages:
  stage: deploy
  needs:
    - job: yard
      artifacts: true
  script:
    - cp -r yard public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
